dec-teame/stutodo

shio_for_issue1.txt

[add] shio text file

---

shio_for_issue1.txt

[add] issue1.txt

---

kawano.txt

[add] kawano.txt

---

app/Models/Todo.php
app/Models/User.php

@saaa-padae @kawataharaA @shvalin1 
- TodoのModelを編集しました。
- guarded追加
- hasmanyの追加

[add] App/Models/Todoにguardedを追加 App/Models/Userにhasmanyを追加

---

database/factories/TodoFactory.php

[fix] TodosFactory.php to TodoFactory.php

---

app/Http/Controllers/TaskController.php
routes/web.php

＃19のブランチですが、issue#18のコントローラーの作成と
issue#19のルーティングの設定をしました。

[add] create Taskcontroller #18

---

app/Http/Controllers/TodoController.php
routes/web.php

@saaa-padae 
Model名がTodoのため、ControllerはTaskControllerからTodoControllerに変更します。
Closes #41

[fix] TaskControllerをTodoControllerに変更

---

routes/web.php

@kawataharaA @saaa-padae @shvalin1 
ユーザー認証の連携を実装しました。
変更したファイルはroutes/web.phpです。
Close #17

[add] ユーザー認証の連携を実装

---

resources/views/todo/create.blade.php

- Todo作成画面の入力フィールドにデータ型を指定しました。
- <input type=... >をnumberやdate, textに変更しました。
　
Close #45

[add] Todo作成画面の入力フィールドにデータ型を指定

---

resources/views/todo/create.blade.php

- Todo Createページにplaceholderを設定。
Close #47

issue#47 Todo createページにplaceholderを設定

---

resources/views/todo/create.blade.php

- Todo作成画面のimportanceをプルダウンで選択できるように変更しました。
Close #50

issue#50 Todoの作成画面のimportanceをプルダウンに変更

---

app/Http/Controllers/TodoController.php

- TodoControllerにvalidation機能を追加
Close #49 
- 検証ルールを追加
- between:a, b -> aからbまでの数字
```
'task' => 'required | max:191',
'deadline' => 'required',
'importance' => 'required | integer | between:1,3',
'description' => 'required',
```

issue#49 TodoControllerにvalidation機能を追加

---

resources/views/todo/create.blade.php

- oldヘルパーを追加
- oldヘルパーを用いることで、バリデーションに引っかかた時、前回の値を復元することができる。 
Close #53

issue#53 oldヘルパーを追加

---

app/Http/Controllers/TodoController.php
resources/views/todo/index.blade.php

@SHIO777 @shvalin @saaa-padae 
資料6.10の
・一覧画面に詳細画面へのリンクを作成
・指定した１件のデータを取得する処理を追加
をしてます。
詳細表示画面の作成は「show.blade.php」がないのでまだしてないです。

[add] detail link, process to get

---

app/Http/Controllers/TodoController.php
resources/views/todo/edit.blade.php
resources/views/todo/index.blade.php

@SHIO777 @shvalin1 @saaa-padae 
資料6.12
-一覧画面に編集ボタンを追加
-編集画面に移動する処理の作成
-指定したデータを更新する処理の作成

[add] create button, create action to move

---

package-lock.json
package.json
resources/js/app.js
resources/js/calendar.js
resources/views/calendar.blade.php
routes/web.php

localhost/calendar　と検索バーに打つとただのカレンダーが表示されるようになっています。
Todoのページとは連携できていません。

[add] calendar

---

app/Http/Controllers/CalendarController.php
resources/views/calendar.blade.php
resources/views/layouts/navigation.blade.php
routes/web.php

Issue#77 カレンダー画面を追加

---

app/Http/Controllers/TodoController.php

Issue#80 他のユーザーのtodoも見えてしまう

---

resources/views/todo/show.blade.php

-show.blade.php内のtaskのidを編集した。

[fix] edit id

---

resources/views/todo/index.blade.php

-完了ボタンと未完了ボタンを色だけではなく、形でも区別させた。
Close　#97

[add] 完了ボタンと未完了ボタンの差別化

---

resources/views/todo/index.blade.php

[add] 完了ボタンと未完了ボタンの

---

app/Http/Controllers/TodoController.php

[add] 完了・未完了機能を追加

---

app/Http/Controllers/TodoController.php
resources/views/layouts/navigation.blade.php
routes/web.php

[add] 完了課題一覧を追加しました　#72

---

app/Http/Controllers/TodoController.php

[update] コントローラーにfinishedで条件をつけました

---

app/Http/Controllers/TodoController.php

-完了機能の分離
-isFinishedの作成
Close #108

[clean] 完了の判定

---

app/Http/Controllers/TodoController.php

- finished関数でisFinished関数を、ビット反転(!$変数名)に修正
- これにより、isFinished関数が不要になった。
Close #113

issue#113 [fix] finished関数の修正

---

app/Http/Controllers/TodoController.php

[remove] ddd($data)をコメントアウト

---

package-lock.json
package.json

[[Laravel] オフラインでjQueryを使う](https://qiita.com/AkiYanagimoto/items/4d409ac978bff3f52a75)
```
sail npm install jquery
```

[add] sail npm install jquery #119
